name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Enable RDP
      run: |
        Enable-PSRemoting -Force
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user Ahmaddev123 WinRDP@2025! /add
        net localgroup administrators Ahmaddev123 /add

    - name: Display internal IP
      run: ipconfig

    - name: Display external IP
      run: curl ifconfig.me
